// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypxibmmeecrfgmkemvpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlweGlibW1lZWNyZmdta2VtdnB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0ODU1MDAsImV4cCI6MjA2NjA2MTUwMH0.aYV1GMkjhm8Egj5_o02ND7OW7o9xPYAqsN1VBCa94yM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);